// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] 
/// 
/// 
/// for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL0X6nmIacH7Ersiu6OIVEOIwAY_Mcr1g',
    appId: '1:490061363808:web:3663ebc8b72093842c6105',
    messagingSenderId: '490061363808',
    projectId: 'quizhub321',
    authDomain: 'quizhub321.firebaseapp.com',
    storageBucket: 'quizhub321.firebasestorage.app',
    measurementId: 'G-PF0VDKNK9Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSnzYWallELWAfXiv3ESoXZJFEwpr5JQg',
    appId: '1:490061363808:android:572b1b5e9749ac552c6105',
    messagingSenderId: '490061363808',
    projectId: 'quizhub321',
    storageBucket: 'quizhub321.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLMVnGyGP04S8dCnsDTwc0MI7J_slpJhg',
    appId: '1:490061363808:ios:c82bb672a3bda97e2c6105',
    messagingSenderId: '490061363808',
    projectId: 'quizhub321',
    storageBucket: 'quizhub321.firebasestorage.app',
    iosBundleId: 'com.example.todovalidate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDL0X6nmIacH7Ersiu6OIVEOIwAY_Mcr1g',
    appId: '1:490061363808:web:0df88c6b4de0deb32c6105',
    messagingSenderId: '490061363808',
    projectId: 'quizhub321',
    authDomain: 'quizhub321.firebaseapp.com',
    storageBucket: 'quizhub321.firebasestorage.app',
    measurementId: 'G-FXVY119ER9',
  );
}
