// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt-dqCX6sR72jXLQLKqABYzfDeNlyYF3s',
    appId: '1:943787935354:web:41fe408f907c8e349c9dc3',
    messagingSenderId: '943787935354',
    projectId: 'todo-list-f89f6',
    authDomain: 'todo-list-f89f6.firebaseapp.com',
    storageBucket: 'todo-list-f89f6.firebasestorage.app',
    measurementId: 'G-E3BTTPZ4QY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCb4W-4YStgPVFB4S6ORDq9xOWBEefpJBk',
    appId: '1:943787935354:android:d267b32a7e7a1d4f9c9dc3',
    messagingSenderId: '943787935354',
    projectId: 'todo-list-f89f6',
    storageBucket: 'todo-list-f89f6.firebasestorage.app',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKSzRiPQLXU729Mt7q4twFm7PAA69HpJg',
    appId: '1:943787935354:ios:6337a0c1b6c7987c9c9dc3',
    messagingSenderId: '943787935354',
    projectId: 'todo-list-f89f6',
    storageBucket: 'todo-list-f89f6.firebasestorage.app',
    iosBundleId: 'com.example.todovalidate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBt-dqCX6sR72jXLQLKqABYzfDeNlyYF3s',
    appId: '1:943787935354:web:8b2609fd3c1cd0529c9dc3',
    messagingSenderId: '943787935354',
    projectId: 'todo-list-f89f6',
    authDomain: 'todo-list-f89f6.firebaseapp.com',
    storageBucket: 'todo-list-f89f6.firebasestorage.app',
    measurementId: 'G-FYSTMDFE89',
  );
}
